import Head from 'next/head'
import Image from 'next/image'
import { aboutme } from '../lib/api'
import styles from '../styles/Home.module.css'
import ReactMarkdown from 'react-markdown'


export default function Home(about) {
  
  console.log(typeof about.content)

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ReactMarkdown >{about.content}</ReactMarkdown>
    </div>
  )
}




export async function getStaticProps() {
  const [content, data] = await aboutme()

  return {
    props: {
      data, content
    },
  }
}